cal/urls.py
# from django.conf.urls import url
from . import views
from django.urls import path

app_name = "cal"
urlpatterns = [
    path("index/", views.get_date, name="index"),
    path("<int:tor_id>/calendar/", views.CalendarView.as_view(), name="calendar"),
    path(
        "event/new/<int:tor_id>/<int:day>/<int:month>/<int:year>",
        views.EventNew.as_view(),
        name="event_newer",
    ),
    # path("event/edit/<int:event_id>/", views.event, name="event_edit"),
    path(
        "event_details/<int:pk>/<int:tor_pk>",
        views.EventDetail.as_view(),
        name="event_detail",
    ),
    path(
        "event_delete/<int:pk>/<int:tor_pk>",
        views.EventDelete.as_view(),
        name="event_delete",
    ),
]

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path("", views.home, name="homepage"),
    path("about/", views.about, name="about"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_views.ProfileView.as_view(), name="profile"),
    path("tory_list/", views.TorListView.as_view(), name="tory_list"),
    path("tory_list/new/", views.TorCreateView.as_view(), name="tor_create"),
    path("tory_list/update/<int:pk>", views.TorUpdateView.as_view(), name="tor_update"),
    path("tory_list/delete/<int:pk>", views.TorDeleteView.as_view(), name="tor_delete"),
]

strzelnica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cal/", include("cal.urls")),
    path("register/", include("users.urls")),
]

core/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Tor(models.Model):
    nazwa = models.CharField(max_length=100)
    opis = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.nazwa


# Create your models here.

core/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse
from django.shortcuts import render
from .models import Tor
from django.views.generic.list import ListView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def home(request):
    return render(
        request, "core/home.html", {"title": "Home", "tory": Tor.objects.all()}
    )


def about(request):
    return render(request, "core/about.html")


class TorListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Tor
    template_name = "core/tory_list.html"
    context_object_name = "tory"

    def test_func(self):
        return self.request.user.is_staff


class TorCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Tor
    template_name = "core/tor_form.html"
    fields = ["nazwa", "opis"]

    def get_success_url(self):
        return reverse("tory_list")

    def test_func(self):
        return self.request.user.is_staff


class TorUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Tor
    template_name = "core/tor_form.html"
    fields = ["nazwa", "opis"]

    def get_success_url(self):
        return reverse("tory_list")

    def test_func(self):
        return self.request.user.is_staff


class TorDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tor
    template_name = "core/tor_delete_confirm.html"

    def get_success_url(self):
        return reverse("tory_list")

    def test_func(self):
        return self.request.user.is_staff

core/templates/core/about.html
{% extends 'core/base.html' %}
{% block content %}
<h1>To jest strona zrobiona przez Maćka</h1>
<p>Tu będzie dodatkowy opis</p>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	    <link rel="stylesheet" type="text/css" href="{% static 'core/base.css' %}" />

	    {% block additional_stylesheet %}
	    {% endblock %}

		{% if title %}
		<title>Strzelnica - {{  title }}</title>
		{% else %}
		<title>Strzelnica</title>
		{% endif %}
	</head>
	<body>

	    <header class="site-header">
	        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	            <div class="container">
	                <a class="navbar-brand mr-4" href="/">Strzelnica</a>
	                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	                    <span class="navbar-toggler-icon"></span>
	                </button>
	                <div class="collapse navbar-collapse" id="navbarToggle">
	                    <div class="navbar-nav mr-auto">
	                        <a class="nav-item nav-link" href="{% url 'homepage' %}">Strona domowa</a>
	                        <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
	                    </div>
	                    <!-- Navbar Right Side -->
	                    <div class="navbar-nav">
	                    	{% if user.is_authenticated %}
		                    	<a class="nav-item nav-link" href="{% url 'profile' %}">Profil</a>
		                    	<a class="nav-item nav-link" href="{% url 'logout' %}">Wyloguj</a>
		                    	{% if user.is_staff %}
			                    	<a class="nav-item nav-link" href="{% url 'tory_list' %}">Lista torów</a>
			                    	<a class="nav-item nav-link" href="{% url 'tor_create' %}">Dodaj tor</a>
			                    {% endif %}
		                    {% else %}
			                    <a class="nav-item nav-link" href="{% url 'login' %}">Logowanie</a>
		                        <a class="nav-item nav-link" href="{% url 'register' %}">Zarejestruj się</a>
		                    {% endif %}
	                    </div>
	                </div>
	            </div>
	        </nav>
	    </header>


		<main role="main" class="container">
		     <div class="row">
		         <div class="col-md-12">
		         	{% if messages %}
		         		{% for message in messages %}
		         		 <div class="alert alert-{{ message.tags }}">
		         		 	{{ message }}
		         		 </div>
		         		{% endfor %}
		         	{% endif %}
		            {% block content %}{% endblock %}
		         </div>
		     </div>
		</main>

	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	    {% block additional_script %}
	    {% endblock %}
	</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% block content %}
    {% for tor in tory %}
        <article class="media content-section">
            <div class="media-body">
                <h2><a class="article-title" href="{% url 'cal:calendar' tor.id %}">{{ tor.nazwa }}</a></h2>
                <p class="article-content">{{ tor.opis }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock %}

core/templates/core/tor_delete_confirm.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Usuń tor</legend>
					<h3>Czy jesteś pewien, że chcesz usunąć {{ object.nazwa }}</h3>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Tak</button>
				<a class="btn btn-outline-secondary" href="{% url 'tory_list' %}">Anuluj</a>
			</div>
		</form>
	</div>
{% endblock %}

core/templates/core/tor_form.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Nowy tor</legend>
					{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Zapisz</button>
			</div>
		</form>
	</div>
{% endblock %}

core/templates/core/tory_list.html
{% extends 'core/base.html' %}
{% block content %}
    {% for tor in tory %}
        <article class="media content-section">
            <div class="media-body">
                <h2><a class="article-title" href="{% url 'tor_update' tor.id %}">{{ tor.nazwa }}</a></h2>
                <p class="article-content">{{ tor.opis }}</p>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tor_update' tor.id %}">Modyfikuj</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'tor_delete' tor.id %}">Usuń</a>
            </div>
        </article>
    {% endfor %}
{% endblock %}